image: registry.gitcity.sk/cakehub/cakeapp:fpm

stages:
    - prepare
    - build
    - test
    - post-test
    - deploy

.run-on-do-docker: &run-on-do-docker
    tags:
        - digitalocean
        - docker
        - a

.default-variables: &default-variables
    DB_CONNECTION: pgsql
    DB_HOST: postgres
    DB_PORT: 5432
    DB_DATABASE: "gitcity-test"
    DB_USERNAME: postgres
    DB_PASSWORD: "5RGGjwubxdqyF6dL"
    APP_KEY: "base64:i401pX1nVrGs5i4eWFoxB67N5mkfVhrF9kxqKSkj15o="
    APP_ENV: testing

.postgres-variables: &postgres-variables
    variables:
        <<: *default-variables
        POSTGRES_PASSWORD: "5RGGjwubxdqyF6dL"
        POSTGRES_DB: "gitcity-test"

.default-cache: &default-cache
    key: "cake-app-with-php-7"
    paths:
        - vendor/

.push-cache: &push-cache
    cache:
        <<: *default-cache
        policy: push

.pull-cache: &pull-cache
    cache:
        <<: *default-cache
        policy: pull

composer:install-dependencies:
    <<: *postgres-variables
    <<: *push-cache
    stage: prepare
    services:
        - postgres
    script:
        - composer self-update
        - composer -V
        - composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader
    <<: *run-on-do-docker

php:postgres-migrate:
    <<: *postgres-variables
    <<: *pull-cache
    stage: test
    services:
        - postgres
    script:
        - php artisan migrate
        - php artisan migrate:status
    <<: *run-on-do-docker

php:postgres-phpunit:
    <<: *postgres-variables
    <<: *pull-cache
    stage: test
    services:
        - postgres
    script:
        - composer install --no-progress
        - php artisan migrate
        - phpunit --coverage-text --colors=never
    <<: *run-on-do-docker

php:postgres-phpcs:
    <<: *postgres-variables
    <<: *pull-cache
    stage: post-test
    services:
        - postgres
    script:
        # - composer require cakephp/cakephp-codesniffer:dev-master
        - composer install --no-progress
        - chmod +x vendor/bin/phpcs
        - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./app ./tests ./routes ./database
    allow_failure: true
    <<: *run-on-do-docker

build image:
    <<: *pull-cache
    image: docker:latest
    services:
        - docker:dind
    stage: build
    before_script:
        - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" "$CI_REGISTRY" --password-stdin
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
    <<: *run-on-do-docker
    only:
        - master

deploy:to-docker-cloud:
    image: docker:latest
    services:
        - docker:dind
    stage: deploy
    before_script:
        - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" "$CI_REGISTRY" --password-stdin
        - echo "$CLOUD_REGISTRY_SECRET" | docker login -u "maymeow" --password-stdin
    script:
        - docker pull "$CI_REGISTRY_IMAGE"
        - docker tag "$CI_REGISTRY_IMAGE" maymeow/webapp-ce:latest
        - docker push maymeow/webapp-ce:latest
    <<: *run-on-do-docker
    only:
        - master

deploy:tags-to-docker-cloud:
    <<: *pull-cache
    image: docker:latest
    services:
        - docker:dind
    stage: deploy
    before_script:
        - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" "$CI_REGISTRY" --password-stdin
        - echo "$CLOUD_REGISTRY_SECRET" | docker login -u "maymeow" --password-stdin
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
        - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
        - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" maymeow/webapp-ce:"$CI_COMMIT_REF_NAME"
        - docker push maymeow/webapp-ce:"$CI_COMMIT_REF_NAME"
    <<: *run-on-do-docker
    only:
        - tags
