image: registry.gitcity.sk/gitcity-sk/gitcity-build-images:php-7.1-fpm-redis-phpunit-6.5.6

stages:
    - prepare
    - build
    - test
    - post-test
    - deploy

# Tags
.run-on-do-docker: &run-on-do-docker
    tags:
        - digitalocean
        - docker
        - a

# Cache configuration
.default-cache: &default-cache
    paths:
        - vendor/

.push-cache: &push-cache
    cache:
        <<: *default-cache
        key: "cake-app-with-php-7"
        policy: push

.pull-cache: &pull-cache
    cache:
        <<: *default-cache
        key: "cake-app-with-php-7"
        policy: pull

.push-cache-dev: &push-cache-dev
    cache:
        <<: *default-cache
        key: "cake-app-with-php-7-dev"
        policy: push

.pull-cache-dev: &pull-cache-dev
    cache:
        <<: *default-cache
        key: "cake-app-with-php-7-dev"
        policy: pull

# Services configuration
.postgres-variables: &postgres-service
    variables:
        POSTGRES_PASSWORD: "5RGGjwubxdqyF6dL"
        POSTGRES_DB: homestead
    services:
        - postgres

.mysql-variables: &mysql-service
    variables:
        MYSQL_USER: homestead
        MYSQL_DATABASE: homestead
        MYSQL_PASSWORD: "5RGGjwubxdqyF6dL"
        MYSQL_ROOT_PASSWORD: "5RGGjwubxdqyF6dL"
    services:
        - mariadb

# PHP UNIT tests configuration
.phpunit-tests: &phpunit-tests
    stage: test
    script:
        - php artisan key:generate
        - php artisan config:cache
        - phpunit --coverage-text --colors=never
    retry: 2
    artifacts:
        untracked: true
        paths:
            - ./storage/logs
        when: on_failure
        expire_in: 1 week

.phpunit-pg-tests: &phpunit-pg-tests
    <<: *postgres-service
    <<: *pull-cache-dev
    <<: *run-on-do-docker
    <<: *phpunit-tests
    before_script:
        - cp .env.testing.pgsql .env
        
.phpunit-mysql-tests: &phpunit-mysql-tests
    <<: *mysql-service
    <<: *pull-cache-dev
    <<: *run-on-do-docker
    <<: *phpunit-tests
    before_script:
        - cp .env.testing.mysql .env

# PHPCS configuration
.phpcs-tests: &phpcs-tests
    <<: *pull-cache-dev
    <<: *run-on-do-docker
    stage: post-test
    script:
        - chmod +x vendor/bin/phpcs
        - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./app ./tests ./routes ./database
    allow_failure: true

# composer Update
.composer-install: &composer-install
    <<: *run-on-do-docker
    stage: prepare
    before_script:
        - composer self-update
        - composer -V

# Prepare
composer-install: 
    <<: *composer-install
    <<: *push-cache-dev
    script:
        - composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

composer-install-dev:
    <<: *composer-install
    <<: *push-cache-dev
    script:
        - composer install --no-ansi --no-interaction --no-progress --no-scripts

# Tests
phpunit-pg-tests 1 1: *phpunit-pg-tests

phpunit-mysql-tests 1 1: *phpunit-mysql-tests

phpcs-tests 1 1: *phpcs-tests

# Build
build image:
    <<: *pull-cache
    image: docker:latest
    services:
        - docker:dind
    stage: build
    before_script:
        - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" "$CI_REGISTRY" --password-stdin
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
    <<: *run-on-do-docker
    only:
        - master

# Deploy
deploy:to-docker-cloud:
    image: docker:latest
    services:
        - docker:dind
    stage: deploy
    before_script:
        - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" "$CI_REGISTRY" --password-stdin
        - echo "$CLOUD_REGISTRY_SECRET" | docker login -u "maymeow" --password-stdin
    script:
        - docker pull "$CI_REGISTRY_IMAGE"
        - docker tag "$CI_REGISTRY_IMAGE" maymeow/webapp-ce:latest
        - docker push maymeow/webapp-ce:latest
    <<: *run-on-do-docker
    only:
        - master

deploy:tags-to-docker-cloud:
    <<: *pull-cache
    image: docker:latest
    services:
        - docker:dind
    stage: deploy
    before_script:
        - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" "$CI_REGISTRY" --password-stdin
        - echo "$CLOUD_REGISTRY_SECRET" | docker login -u "maymeow" --password-stdin
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
        - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
        - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" maymeow/webapp-ce:"$CI_COMMIT_REF_NAME"
        - docker push maymeow/webapp-ce:"$CI_COMMIT_REF_NAME"
    <<: *run-on-do-docker
    only:
        - tags
